#!/bin/bash

source $(dirname $0)/ttk.inc.sh

langs=$*
option_project="--project=$project"

if [ $# -eq 0 ]; then
	langs=$(all_langs)
elif [ $# -eq 1 -a -z "${1//[0-9]/}" ]; then
	langs=$(all_langs $1)
fi

git stash --quiet
git pull --rebase
git checkout
git stash pop --quiet

sync_stores $langs
rsync_files_get $langs
disassemble_phase $langs
