#!/bin/bash

source $(dirname $0)/ttk.inc.sh

if [[ $# -ne 2 ]]; then
	echo "$(basename $0) <--since> <lang>"
	echo "$(basename $0) <lang> <changeid>"
	exit 1
fi

if [[ $1 == "--since" ]]; then
	last_commit_filename=LAST_COMMIT_$(workon_current)_*
	lang=$2
	list_contributors $lang $(cat $last_commit_filename)
	count_contributors $lang $(cat $last_commit_filename)
	commit_author $lang $(cat $last_commit_filename)
	git_commit_author $lang $(cat $last_commit_filename)
else
	lang=$1
	changeid=$2
	list_contributors $lang $changeid
fi
