#!/bin/bash

push="yes"
#push=

source $(dirname $0)/ttk.inc.sh
stop_if_running
mk_lock_file

if [[ $# -lt 1 ]]; then
	echo "$(basename $0) <--since|[lang|changeid>"
	echo "We don't allow all commits as we might overwrite other peoples work"
	exit 1
fi

if [[ $1 == "--since" ]]; then
	stop_if_no_last_commit
	mk_new_commit_file
	langs=$(which_langs $(cat $last_commit_file))
	[[ $langs ]] && logger_file commit auto "$(cat $last_commit_file)>$(cat $new_commit_file)" "{ $langs }"
	auto="yes"
else
	langs=$(which_langs $*)
	[[ $langs ]] && logger_file commit manual "{ $* }" "{ $langs }"
fi

if [[ ! $langs ]]; then
	rm_lock_file
	exit
fi


for lang in $langs
do
	mozlang=$(get_language_upstream $lang)
	pootlelang=$(get_language_pootle $lang)
	ttk-get $lang
	# FIXME handle initialised languages
	(
		cd ${base_dir}/$pootlelang
		if [[ $PRODUCT_DIRS ]]; then
			for dir in $PRODUCT_DIRS $RETIRED_PRODUCT_DIRS
			do
				git add -A $dir
			done
		else
			git add -A .
		fi
		git commit -m "[$pootlelang] pull from Pootle ($project)"
	)
	ttk-build --vc $lang
	(cd ${base_dir}; git checkout $pootlelang)
	(
		cd ${base_dir}/build/${L10N_VER}/$mozlang
		hg addremove $PRODUCT_DIRS $RETIRED_PRODUCT_DIRS
		hg revert -C $OTHER_EXCLUDED_DIRS
		hg commit -m "[$mozlang] update from Pootle ($project)"
		[[ $push ]] && hg push
	)
done

[[ $push ]] && git push
[[ $auto ]] && update_last_commit_file
rm_lock_file
