#!/bin/bash

source $(dirname $0)/ttk.inc.sh

langs=$(which_langs $*)
if [ ! "$langs" ]; then
	log_warning "No languages to process"
else
	sync_stores $langs
	rsync_files_get $langs
	disassemble_phase $langs
fi
