#!/bin/bash

source $(dirname $0)/ttk.inc.sh

#push="yes"
push=

ttk-build templates
(
	for dir in $PRODUCT_DIRS $RETIRED_PRODUCT_DIRS
	do
		cd ${base_dir}/templates
		git add -A $dir
		cd ${base_dir}/templates-en-US
		git add -A $dir
	done
)
git diff --quiet --cached --exit-code templates
if [ $? -ne 0 ]; then
	git commit -m "Templates: update ($project)" templates templates-en-US
	ttk-put templates
	id=$(ttk-changeid)
	ttk-get
	git add $(ttk-langs)
	git commit -m "Various: pre templates update ($project)"
	ttk-build --no-compare-locales --no-xpi --no-tarball
	git add $(ttk-langs)
	git commit -m "All: update against templates ($project)"
	ttk-put --keep=$id
fi
[[ $push ]] && git push
