#!/bin/bash

source $(dirname $0)/ttk.inc.sh
stop_if_running

if [ $# -lt 1 ]; then
	log_warning "The following commands are available"
	[ -d ${config_dir}/cmds ] && ls ${config_dir}/cmds
	[ -d  ${config_base_dir}/cmds ] && ls ${config_base_dir}/cmds
	exit
fi

command=$1
shift
options=$*

if [ -f ${config_dir}/cmds/$command ]; then
	source ${config_dir}/cmds/$command
elif [ -f ${config_base_dir}/cmds/$command ]; then
	source ${config_base_dir}/cmds/$command
else
	log_error "No command: $command"
fi

$command $options
