#!/bin/bash

source ttk.inc.sh

function process()
{
	testtype=$1
	pofilter --progress=none -t $testtype en_ZA en_ZA-$testtype
	sed -i "/^# (pofilter)/d" $(find en_ZA-$testtype -name "*.po")
	for po in $(find en_ZA-$testtype -name "*.po")
	do
		msgattrib --clear-fuzzy $po > $po.2
		mv $po.2 $po
	done
	podebug --progress=none --rewrite=blank en_ZA-$testtype en_ZA-$testtype-blank
	podebug --progress=none --rewrite=en en_ZA-$testtype-blank en_ZA-$testtype-en
	pofilter --progress=none -t musttranslatewords --musttranslatefile=words-must-en_ZA en_ZA-$testtype-en en_ZA-$testtype-en-must
	vim $(find en_ZA-$testtype-en-must -name "*.po")
	sed -i "/^# (pofilter)/d" $(find en_ZA-$testtype-en-must -name "*.po")
	pomerge --progress=none -t en_ZA-$testtype-en en_ZA-$testtype-en-must en_ZA-$testtype-en
	pomerge --progress=none -t en_ZA en_ZA-$testtype-en en_ZA
	rm -rf en_ZA-$testtype*
}

function usage() {
	echo "Usage: make-en_ZA"
	echo
	echo "Create an English (South Africa) version"
	exit 1
}

function make-en_ZA() {
	polang=$(get_language_pootle en_ZA)
	process untranslated
	process isfuzzy
	clean_po $polang
}
