#!/bin/bash

require hg

_find_config_base_dir
BUILD_DIR="${base_dir}/build"
L10N_DIR="${BUILD_DIR}/l10n"

function usage() {
	echo "Usage: mercurial [option] [language]"
	echo
	echo " --clone - clone or reclone preserving .hg/hgrc"
	echo
	exit 1
# TODO
#--pull - do a pull without any changes
#--reset - reset and remove any changed or new files
#--username - script to edit the username data
#--diff - do a diff for the language
#--commit - commit for the language
#--push - push the data upstream
#--status - status of the directory
#--command - run an hg command
#--addremove - run a simple addremove across the language
#--check - check what the status for various languages is
#        Should show uncommited files
#        Upstream ahead of current
}

function _get_option() {
	local option=$1
	case $1 in
		--clone)
			command="_clone"
			;;
		*)
			usage
			;;
	esac
	echo $command
}

function _clone(){
	mozlang=$(get_language_upstream $*)
	[ -f $L10N_DIR/$mozlang/.hg/hgrc ] && mv $L10N_DIR/$mozlang/.hg/hgrc $L10N_DIR/$mozlang.hgrc
	rm -rf $L10N_DIR/$mozlang
	hg clone http://hg.mozilla.org/releases/l10n/mozilla-aurora/$mozlang $L10N_DIR/$mozlang
	[ -f $L10N_DIR/$mozlang.hgrc ] && mv $L10N_DIR/$mozlang.hgrc $L10N_DIR/$mozlang/.hg/hgrc
}

function mercurial() {
	local option=$1
	shift
	[ $# -eq 0 ] && usage
	command=$(_get_option $option)
	[ $? -ne 0 ] && usage
	local langs=$*
	for lang in $langs
	do
		$command $lang
	done
}
