#!/bin/bash

require hg

_find_config_base_dir
BUILD_DIR="${base_dir}/build"
L10N_DIR="${BUILD_DIR}/${L10N_VER}"

function usage() {
	echo "Usage: mercurial [option] [language]"
	echo
	echo " --clone - clone or reclone preserving .hg/hgrc"
	echo
	exit 1
# TODO
#--pull - do a pull without any changes
#--reset - reset and remove any changed or new files
#--username - script to edit the username data
#--diff - do a diff for the language
#--commit - commit for the language
#--push - push the data upstream
#--status - status of the directory
#--command - run an hg command
#--addremove - run a simple addremove across the language
#--check - check what the status for various languages is
#        Should show uncommited files
#        Upstream ahead of current
}

function _get_option() {
	local option=$1
	case $1 in
		--clone)
			command="_clone _set_author _set_push_repo _set_rebase_extension"
			;;
		--set-author)
			command="_set_author"
			;;
		--set-push-repo)
			command="_set_push_repo"
			;;
		--set-rebase-extension)
			command="_set_rebase_extension"
			;;
		*)
			usage
			;;
	esac
	echo $command
}

function _clone(){
	mozlang=$(get_language_upstream $*)
	[ -f $L10N_DIR/$mozlang/.hg/hgrc ] && mv $L10N_DIR/$mozlang/.hg/hgrc $L10N_DIR/$mozlang.hgrc
	rm -rf $L10N_DIR/$mozlang
	hg clone http://hg.mozilla.org/${L10N_VER}/$mozlang $L10N_DIR/$mozlang
	[ -f $L10N_DIR/$mozlang.hgrc ] && mv $L10N_DIR/$mozlang.hgrc $L10N_DIR/$mozlang/.hg/hgrc
}

function _set_push_repo(){
	mozlang=$(get_language_upstream $*)
	hgrc=$L10N_DIR/$mozlang/.hg/hgrc
	current_pushrepo=$(egrep "^default-push" $hgrc)
	if [ "$current_pushrepo" != "" ]; then
		log_warning "Push repo already set set to $current_pushrepo"
	else
		current_defaultrepo=$(egrep "^default =" $hgrc)
		new_pushrepo=$(sed -i "/default =/p;s/default/default-push/;s/http:/ssh:/" $hgrc)
	fi
}

function _set_author(){
	mozlang=$(get_language_upstream $*)
	hgrc=$L10N_DIR/$mozlang/.hg/hgrc
	current_username=$(egrep "^username" $hgrc)
	if [ "$current_username" != "" ]; then
		log_warning "Author already set set to $current_username"
	else
		cat >> $hgrc <<-EOF

		[ui]
		username = $mozlang team [Pootle] <https://wiki.mozilla.org/L10n:Teams:$mozlang>
		EOF
	fi
}

function _set_rebase_extension(){
	mozlang=$(get_language_upstream $*)
	hgrc=$L10N_DIR/$mozlang/.hg/hgrc
	has_extensions=$(grep -q "\[extensions\]" $filename)
	has_rebase_extension=$(grep -q "rebase =" $filename)
	if [ $has_extensions -eq 0 ] &&	[ $has_rebase_extension -eq 0 ]; then
		log_warning "Rebase extension already enabled for $mozlang"
	else
		if [ $has_extensions -ne 0 ] &&	[ $has_rebase_extension -ne 0 ]; then

			cat >> $hgrc <<-EOF

			[extensions]
			rebase =
			EOF
		else
			log_warning "Possibly wrong or duplicate [extensions] in `hgrc` for $mozlang. Fix manually."
		fi
	fi
}

function mercurial() {
	local option=$1
	shift
	[ $# -eq 0 ] && usage
	command=$(_get_option $option)
	[ $? -ne 0 ] && usage
	local langs=$*
	for lang in $langs
	do
		for cmd in $command
		do
			$cmd $lang
		done
	done
}
